#!/usr/bin/env python3
"""Generate crates/pycheckers/src/depdata.rs from the pinned pylint's
deprecation tables + DUNDER_METHODS, pre-filtered exactly as the checkers do
at runtime (sys.version_info gates; run under the pinned 3.12 venv with
PYTHONHASHSEED=0 so set iteration orders are reproduced)."""
import sys

assert sys.version_info[:2] == (3, 12), sys.version_info
from pylint.checkers.stdlib import (
    DEPRECATED_METHODS, DEPRECATED_ARGUMENTS, DEPRECATED_DECORATORS,
    DEPRECATED_CLASSES, DEPRECATED_ATTRIBUTES)
from pylint.checkers.imports import DEPRECATED_MODULES
from pylint.constants import DUNDER_METHODS, UNNECESSARY_DUNDER_CALL_LAMBDA_EXCEPTIONS

out = []
out.append("//! GENERATED by harness/gen_deprecated_rs.py (pinned venv, PYTHONHASHSEED=0).")
out.append("//! Deprecation data effective at sys.version_info (3,12,12) + DUNDER_METHODS")
out.append("//! at config py-version (3,12). Set/dict iteration orders preserved.")
out.append("")

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

# --- stdlib __init__ filtering (stdlib.py:608-630) ---
meths = set()
for since, funcs in DEPRECATED_METHODS[sys.version_info[0]].items():
    if since <= sys.version_info:
        meths.update(funcs)
out.append("pub static DEPRECATED_METHODS: &[&str] = &[")
for m in meths:  # set iteration order, seed 0
    out.append(f'    "{esc(m)}",')
out.append("];")
out.append("")

args = {}
for since, mapping in DEPRECATED_ARGUMENTS.items():
    if since <= sys.version_info:
        args.update(mapping)
out.append("pub static DEPRECATED_ARGUMENTS: &[(&str, &[(i64, &str)])] = &[")
for k, v in args.items():
    pairs = ", ".join(f'({-1 if p is None else p}, "{esc(n)}")' for p, n in v)
    out.append(f'    ("{esc(k)}", &[{pairs}]),')
out.append("];")
out.append("")

decs = set()
for since, d in DEPRECATED_DECORATORS.items():
    if since <= sys.version_info:
        decs.update(d)
out.append("pub static DEPRECATED_DECORATORS: &[&str] = &[")
for d in decs:
    out.append(f'    "{esc(d)}",')
out.append("];")
out.append("")

classes = {}
for since, mapping in DEPRECATED_CLASSES.items():
    if since <= sys.version_info:
        classes.update(mapping)   # module -> set replaced wholesale (bug kept)
out.append("pub static DEPRECATED_CLASSES: &[(&str, &[&str])] = &[")
for mod, names in classes.items():
    inner = ", ".join(f'"{esc(n)}"' for n in names)  # set order, seed 0
    out.append(f'    ("{esc(mod)}", &[{inner}]),')
out.append("];")
out.append("")

attrs = set()
for since, a in DEPRECATED_ATTRIBUTES.items():
    if since <= sys.version_info:
        attrs.update(a)
out.append("pub static DEPRECATED_ATTRIBUTES: &[&str] = &[")
for a in attrs:
    out.append(f'    "{esc(a)}",')
out.append("];")
out.append("")

# --- imports deprecated_modules (imports.py:514-522): set(config) | data ---
mods = set()
for since, m in DEPRECATED_MODULES.items():
    if since <= sys.version_info:
        mods.update(m)
out.append("pub static DEPRECATED_MODULES: &[&str] = &[")
for m in mods:
    out.append(f'    "{esc(m)}",')
out.append("];")
out.append("")

# --- DUNDER_METHODS at config py-version (3,12) (dunder_methods.py:47-51) ---
dunder = {}
for since, mapping in DUNDER_METHODS.items():
    if since <= (3, 12):
        dunder.update(mapping)
out.append("pub static DUNDER_METHODS: &[(&str, &str)] = &[")
for k, v in dunder.items():
    out.append(f'    ("{esc(k)}", "{esc(v)}"),')
out.append("];")
out.append("")

out.append("pub static DUNDER_LAMBDA_EXCEPTIONS: &[&str] = &[")
for k in UNNECESSARY_DUNDER_CALL_LAMBDA_EXCEPTIONS:
    out.append(f'    "{esc(k)}",')
out.append("];")

path = "crates/pycheckers/src/depdata.rs"
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {path}: {len(meths)} methods, {len(args)} arg-entries, "
      f"{len(decs)} decorators, {len(classes)} class-modules, {len(attrs)} attrs, "
      f"{len(mods)} modules, {len(dunder)} dunders", file=sys.stderr)
