#!/usr/bin/env python
"""Generate crates/pyinfer/src/ext_templates.rs from the pinned astroid brains.

Captures the EXACT (post-dedent) source each register_module_extender template
passes to astroid.builder.parse / AstroidBuilder.string_build, by patching the
builder before importing the brain modules. The emitted Rust file holds
(module_name, source) pairs in astroid registration order.

Multiprocessing is special: _multiprocessing_transform builds TWO parses (the
extension template + the DefaultContext/BaseContext probe); we emit them as
MP_TEMPLATE and MP_PROBE and the Rust side replays the BoundMethod loop.

Run: .venv-pylint/bin/python harness/gen_ext_templates.py
"""
import sys
import textwrap
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

import astroid.builder as builder  # noqa: E402

_real_parse = builder.parse
_captured = []  # source strings in parse order
_depth = [0]  # >0: inside a captured top-level build (nested builds ignored)


def _spy_parse(code, module_name="", path=None, apply_transforms=True):
    if _depth[0] == 0:
        _captured.append(textwrap.dedent(code))
    _depth[0] += 1
    try:
        return _real_parse(code, module_name, path, apply_transforms)
    finally:
        _depth[0] -= 1


builder.parse = _spy_parse

_real_string_build = builder.AstroidBuilder.string_build


def _spy_string_build(self, data, modname="", path=None):
    if _depth[0] == 0:
        _captured.append(data)
    _depth[0] += 1
    try:
        return _real_string_build(self, data, modname, path)
    finally:
        _depth[0] -= 1


builder.AstroidBuilder.string_build = _spy_string_build


# flush the lazy builtins bootstrap (str/bytes stub builds) before capturing
_depth[0] += 1
_real_parse("pass")
_depth[0] -= 1
_captured.clear()


def capture(fn):
    start = len(_captured)
    fn()
    got = _captured[start:]
    return got


from astroid.brain import (  # noqa: E402
    brain_crypt,
    brain_ctypes,
    brain_curses,
    brain_hashlib,
    brain_http,
    brain_multiprocessing,
    brain_numpy_core_einsumfunc,
    brain_numpy_core_fromnumeric,
    brain_numpy_core_multiarray,
    brain_numpy_core_numeric,
    brain_numpy_core_numerictypes,
    brain_numpy_core_umath,
    brain_numpy_ma,
    brain_numpy_random_mtrand,
    brain_re,
    brain_signal,
    brain_ssl,
    brain_subprocess,
    brain_threading,
    brain_unittest,
)

entries = []  # (rust_const_name, module_name, source)


def one(name, modname, fn):
    got = capture(fn)
    assert len(got) == 1, (name, len(got))
    entries.append((name, modname, got[0]))


one("HASHLIB", "hashlib", brain_hashlib._hashlib_transform)
one("CRYPT", "crypt", brain_crypt._re_transform)
one("CTYPES", "ctypes", brain_ctypes.enrich_ctypes_redefined_types)
one("CURSES", "curses", brain_curses._curses_transform)
one("SUBPROCESS", "subprocess", brain_subprocess._subprocess_transform)
one("THREADING", "threading", brain_threading._thread_transform)
one("SIGNAL", "signal", brain_signal._signals_enums_transform)
one("SSL", "ssl", brain_ssl.ssl_transform)
one("RE", "re", brain_re._re_transform)
one("HTTP", "http", brain_http._http_transform)
one("HTTP_CLIENT", "http.client", brain_http._http_client_transform)
one("MP_MANAGERS", "multiprocessing.managers",
    brain_multiprocessing._multiprocessing_managers_transform)
one("NUMPY_CORE_UMATH", "numpy.core.umath",
    brain_numpy_core_umath.numpy_core_umath_transform)
one("NUMPY_CORE_FROMNUMERIC", "numpy.core.fromnumeric",
    brain_numpy_core_fromnumeric.numpy_core_fromnumeric_transform)
one("NUMPY_CORE_MULTIARRAY", "numpy.core.multiarray",
    brain_numpy_core_multiarray.numpy_core_multiarray_transform)
one("NUMPY_CORE_NUMERIC", "numpy.core.numeric",
    brain_numpy_core_numeric.numpy_core_numeric_transform)
one("NUMPY_CORE_NUMERICTYPES", "numpy.core.numerictypes",
    brain_numpy_core_numerictypes.numpy_core_numerictypes_transform)
one("NUMPY_CORE_EINSUMFUNC", "numpy.core.einsumfunc",
    brain_numpy_core_einsumfunc.numpy_core_einsumfunc_transform)
one("NUMPY_MA", "numpy.ma", brain_numpy_ma.numpy_ma_transform)
one("NUMPY_RANDOM_MTRAND", "numpy.random.mtrand",
    brain_numpy_random_mtrand.numpy_random_mtrand_transform)

# unittest: the real template is `from .async_case import ...` (relative);
# our template modules are package=False so emit the absolute equivalent.
entries.append(("UNITTEST", "unittest",
                "\nfrom unittest.async_case import IsolatedAsyncioTestCase\n"))

# multiprocessing: capture the two parses separately
mp = capture(brain_multiprocessing._multiprocessing_transform)
assert len(mp) >= 2, len(mp)
entries.append(("MP_TEMPLATE", "multiprocessing", mp[0]))
MP_PROBE = mp[1]


def rs_str(s: str) -> str:
    hashes = "#"
    while ('"' + hashes) in s:
        hashes += "#"
    return f'r{hashes}"{s}"{hashes}'


out = [
    "// GENERATED by harness/gen_ext_templates.py from the pinned astroid",
    "// 4.0.4 brain templates -- do not edit by hand.",
    "",
]
for name, modname, src in entries:
    out.append(f"pub static {name}: &str = {rs_str(src)};")
    out.append("")
out.append(f"pub static MP_PROBE: &str = {rs_str(MP_PROBE)};")
out.append("")
out.append("/// (target module name, template source) in astroid registration order.")
out.append("/// multiprocessing handled separately (BM probe).")
out.append("pub static EXTENDERS: &[(&str, &str)] = &[")
for name, modname, _ in entries:
    if name == "MP_TEMPLATE":
        continue
    out.append(f'    ("{modname}", {name}),')
out.append("];")
out.append("")

dest = os.path.join(ROOT, "crates/pyinfer/src/ext_templates.rs")
with open(dest, "w") as fh:
    fh.write("\n".join(out))
print(f"wrote {dest}: {len(entries)} templates")
