#!/usr/bin/env python3
"""Generate crates/pyast/src/codecs_gen.rs: the codec registry needed to
port tokenize.detect_encoding + astroid.builder.open_source_file.

For the pinned CPython (3.12.12), enumerates every codec module under the
`encodings` package plus the alias table (encodings.aliases.aliases):
  - charmap codecs (those with a `decoding_table`) get exact 256-entry
    decode tables (0xFFFE = undefined byte -> UnicodeDecodeError),
  - utf-8 / ascii / latin-1 are decoded natively in Rust,
  - other *text* codecs (utf-16, CJK multi-byte, ...) are marked OtherText
    so the Rust side can pick a documented fallback,
  - bytes<->bytes codecs (base64, zlib, ...) are NotText: Python's open()
    raises LookupError for them, which astroid maps to AstroidSyntaxError.

Usage: .venv-pylint/bin/python harness/gen_codecs_rs.py
"""

import codecs
import os
import pkgutil

import encodings
import encodings.aliases

out_path = os.path.join(
    os.path.dirname(__file__), "..", "crates", "pyast", "src", "codecs_gen.rs"
)

modules = {}  # module name -> (canonical, kind, table|None)
for modinfo in pkgutil.iter_modules(encodings.__path__):
    name = modinfo.name
    if name == "aliases":
        continue
    try:
        info = codecs.lookup(name)
    except LookupError:  # platform-specific (mbcs/oem on Windows)
        continue
    canonical = info.name
    try:
        mod = __import__("encodings." + name, fromlist=["*"])
    except ImportError:
        continue
    table = getattr(mod, "decoding_table", None)
    if not info._is_text_encoding:
        kind = "NotText"
        table = None
    elif canonical == "utf-8":
        kind = "Utf8"
    elif canonical == "ascii":
        kind = "Ascii"
    elif canonical == "iso8859-1":
        kind = "Latin1"
    elif name == "undefined":
        kind = "Undefined"
    elif table is not None and len(table) == 256:
        kind = "Table"
        assert all(ord(c) <= 0x10FFFF for c in table)
    else:
        kind = "OtherText"
        table = None
    modules[name] = (canonical, kind, table)

aliases = sorted(
    (k, v) for k, v in encodings.aliases.aliases.items() if v in modules
)

lines = []
lines.append("//! GENERATED by harness/gen_codecs_rs.py -- do not edit.")
lines.append("//! Codec registry for tokenize.detect_encoding (CPython 3.12.12).")
lines.append("")
lines.append("pub enum CodecKind {")
lines.append("    Utf8,")
lines.append("    Ascii,")
lines.append("    Latin1,")
lines.append("    /// Charmap codec: exact decode table, 0xFFFE = undefined byte.")
lines.append("    Table(&'static [u32; 256]),")
lines.append("    /// Real text codec we do not decode natively (utf-16, CJK, ...).")
lines.append("    OtherText,")
lines.append("    /// The `undefined` codec: every decode raises UnicodeError.")
lines.append("    Undefined,")
lines.append("    /// bytes<->bytes codec: open() raises LookupError (not a text encoding).")
lines.append("    NotText,")
lines.append("}")
lines.append("")
lines.append("pub struct CodecEntry {")
lines.append("    pub canonical: &'static str,")
lines.append("    pub kind: CodecKind,")
lines.append("}")
lines.append("")

# decode tables
tbl_names = {}
for name, (canonical, kind, table) in sorted(modules.items()):
    if kind != "Table":
        continue
    rust = "TBL_" + name.upper()
    tbl_names[name] = rust
    vals = ", ".join(f"0x{ord(c):04X}" for c in table)
    lines.append(f"static {rust}: [u32; 256] = [{vals}];")
lines.append("")

# module entries (sorted for binary search)
lines.append("/// encodings.<module> entries, sorted by module name.")
lines.append("static MODULES: &[(&str, CodecEntry)] = &[")
for name, (canonical, kind, table) in sorted(modules.items()):
    if kind == "Table":
        k = f"CodecKind::Table(&{tbl_names[name]})"
    else:
        k = f"CodecKind::{kind}"
    lines.append(
        f'    ("{name}", CodecEntry {{ canonical: "{canonical}", kind: {k} }}),'
    )
lines.append("];")
lines.append("")

# alias table (sorted for binary search); keys may contain dots.
lines.append("/// encodings.aliases.aliases, sorted by key.")
lines.append("static ALIASES: &[(&str, &str)] = &[")
for k, v in aliases:
    lines.append(f'    ("{k}", "{v}"),')
lines.append("];")
lines.append("")

lines.append(
    """\
/// Port of `codecs.lookup` + `encodings.search_function` name resolution
/// (encodings/__init__.py): normalize, consult the alias table (with a
/// dot->underscore retry), then resolve the codec module by name.
pub fn lookup(normalized: &str) -> Option<&'static CodecEntry> {
    let find_mod = |m: &str| {
        MODULES
            .binary_search_by(|probe| probe.0.cmp(m))
            .ok()
            .map(|i| &MODULES[i].1)
    };
    let find_alias = |a: &str| {
        ALIASES
            .binary_search_by(|probe| probe.0.cmp(a))
            .ok()
            .map(|i| ALIASES[i].1)
    };
    let aliased = find_alias(normalized)
        .or_else(|| find_alias(&normalized.replace('.', "_")));
    // search_function skips candidate module names containing '.'.
    if let Some(a) = aliased {
        if let Some(e) = find_mod(a) {
            return Some(e);
        }
    }
    if !normalized.contains('.') {
        if let Some(e) = find_mod(normalized) {
            return Some(e);
        }
    }
    None
}

/// Port of `encodings.normalize_encoding` preceded by the C-level
/// `codecs.lookup` normalization (lowercase, ' ' -> '_'): keep ASCII
/// alphanumerics and '.', collapse punctuation runs to single '_'.
pub fn normalize_encoding(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut punct = false;
    for c in name.chars() {
        let c = c.to_ascii_lowercase();
        if c.is_ascii_alphanumeric() || c == '.' {
            if punct && !out.is_empty() {
                out.push('_');
            }
            out.push(c);
            punct = false;
        } else {
            punct = true;
        }
    }
    out
}
"""
)

with open(out_path, "w") as fh:
    fh.write("\n".join(lines))
print(f"wrote {out_path}: {len(modules)} modules, {len(aliases)} aliases")
