import os, sys, io, json
flags = open(os.path.expanduser("~/Desktop/Projects/prylint/harness/flags.txt")).read().split()
from pylint.lint.run import Run
sys.stdout, real = io.StringIO(), sys.stdout
run = Run(flags + [os.devnull], exit=False)
sys.stdout = real
linter = run.linter
from pylint.utils.ast_walker import ASTWalker
from pylint.checkers import BaseTokenChecker, BaseRawFileChecker
w = ASTWalker(linter)
cks = linter.prepare_checkers()
for c in cks:
    w.add_checker(c)
out = []
out.append("//! GENERATED by harness/gen_walk_order.py from pylint 4.0.5 under target flags.")
out.append("//! Visit/leave callback order per astroid node kind (lowercase), exactly as")
out.append("//! pylint's ASTWalker dispatches them (checker-sort + dir() order quirks baked in).")
out.append("")
out.append("pub static VISIT_ORDER: &[(&str, &[&str])] = &[")
for cid in sorted(w.visit_events):
    cbs = ", ".join(f'"{cb.__self__.__class__.__name__}.{cb.__func__.__name__}"' for cb in w.visit_events[cid])
    out.append(f'    ("{cid}", &[{cbs}]),')
out.append("];")
out.append("")
out.append("pub static LEAVE_ORDER: &[(&str, &[&str])] = &[")
for cid in sorted(w.leave_events):
    cbs = ", ".join(f'"{cb.__self__.__class__.__name__}.{cb.__func__.__name__}"' for cb in w.leave_events[cid])
    out.append(f'    ("{cid}", &[{cbs}]),')
out.append("];")
out.append("")
raws = [c for c in cks if isinstance(c, BaseRawFileChecker)]
toks = [c for c in cks if isinstance(c, BaseTokenChecker)]
out.append(f'pub static RAW_CHECKERS: &[&str] = &[{", ".join(chr(34)+type(c).__name__+chr(34) for c in raws)}];')
out.append(f'pub static TOKEN_CHECKERS: &[&str] = &[{", ".join(chr(34)+type(c).__name__+chr(34) for c in toks)}];')
path = os.path.expanduser("~/Desktop/Projects/prylint/crates/pycheckers/src/walk_order.rs")
open(path, "w").write("\n".join(out) + "\n")
print(f"{len(w.visit_events)} visit kinds, {len(w.leave_events)} leave kinds -> {path}", file=real)
