#!/usr/bin/env python3
"""Generate crates/pyast/src/stdlib_wildcard.rs: the names astroid's
add_from_names_to_locals adds for `from <stdlib module> import *`.

astroid resolves stdlib modules (and only those, in the harness environment)
via do_import_module() and adds module.public_names() IN ORDER to the
importing scope. We bake those lists for the pinned CPython (3.12.12) +
astroid (4.0.4) so the Rust dump can mirror the behavior without a module
resolver. Regenerate when the pinned interpreter or astroid changes.

Usage: .venv-pylint/bin/python harness/gen_stdlib_wildcard.py
"""

import os
import sys

import astroid

SKIP = {
    "antigravity", "this", "idlelib", "turtledemo", "tkinter", "curses",
    "lib2to3", "__main__",
}

out_path = os.path.join(
    os.path.dirname(__file__), "..", "crates", "pyast", "src", "stdlib_wildcard.rs"
)

modules = sorted(set(sys.stdlib_module_names) - SKIP)
modules = [m for m in modules if not m.startswith("_")]
# common dotted wildcard sources
modules += ["os.path", "collections.abc", "concurrent.futures", "urllib.parse",
            "urllib.request", "urllib.error", "xml.etree.ElementTree",
            "unittest.mock", "importlib.machinery", "importlib.util"]

entries = []
for m in modules:
    try:
        mod = astroid.MANAGER.ast_from_module_name(m)
        names = mod.public_names()
    except Exception:  # noqa: BLE001 - unresolvable: astroid would skip too
        continue
    entries.append((m, names))

with open(out_path, "w") as f:
    f.write("//! GENERATED by harness/gen_stdlib_wildcard.py -- do not edit.\n")
    f.write("//! Names added to locals for `from <stdlib mod> import *`,\n")
    f.write("//! exactly as astroid 4.0.4 + CPython 3.12.12 resolve them\n")
    f.write("//! (Module.public_names() in insertion order).\n\n")
    f.write("pub fn wildcard_names(module: &str) -> Option<&'static [&'static str]> {\n")
    f.write("    Some(match module {\n")
    for m, names in entries:
        joined = ", ".join('"%s"' % n.replace('"', '\\"') for n in names)
        f.write('        "%s" => &[%s],\n' % (m, joined))
    f.write("        _ => return None,\n")
    f.write("    })\n")
    f.write("}\n")

print(f"wrote {out_path} with {len(entries)} modules")
