//! Embed the astroid snapshots (the post-brain view of builtins + C-extension
//! stdlib modules) into the binary so a released prylint needs no repo
//! checkout.
//!
//! Two tables are generated:
//!   * `SNAPSHOTS` — sorted (modname, json) include_str! pairs. The JSON files
//!     in `snapshot/*.json` are the source of truth (regenerated by
//!     harness/gen_snapshot.py). Used by the PRYLINT_SNAPSHOT_DIR-less JSON
//!     fallback and the dev/debug path.
//!   * `SNAPSHOT_BINS` — sorted (modname, &[u8]) include_bytes! pairs pointing
//!     at the compact postcard blobs in `snapshot_bin/*.bin`. These are build
//!     artifacts produced from the JSON by the `gen_snapshot_bin` binary and
//!     committed alongside. The runtime FAST path (snapshot::embedded_bin)
//!     loads these directly into `SnapModule` with no serde_json DOM walk.
//!
//! If a `.bin` is missing (e.g. before the generator has been run once),
//! that module is simply absent from `SNAPSHOT_BINS` and the loader falls back
//! to the JSON for it — so the crate always builds.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let snap_dir = manifest.join("snapshot");
    let bin_dir = manifest.join("snapshot_bin");
    println!("cargo:rerun-if-changed={}", snap_dir.display());
    println!("cargo:rerun-if-changed={}", bin_dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&snap_dir)
        .expect("crates/pyinfer/snapshot must exist (see harness/gen_snapshot.py)")
        .filter_map(|e| {
            let name = e.ok()?.file_name().into_string().ok()?;
            let modname = name.strip_suffix(".json")?;
            (modname != "MANIFEST").then(|| modname.to_string())
        })
        .collect();
    names.sort();

    let mut out = String::new();

    // JSON table (source of truth; dev/debug + fallback). Only modules WITHOUT
    // a committed .bin are embedded as JSON — when every module has a .bin (the
    // normal released state) this table is empty and the ~7.5MB of JSON is kept
    // out of the executable. The on-disk PRYLINT_SNAPSHOT_DIR override and the
    // gen_snapshot_bin generator read JSON straight from disk, so neither needs
    // it embedded.
    out.push_str(
        "/// (modname, json) pairs, sorted by modname for binary_search.\n\
         /// Only modules lacking a committed snapshot_bin/<mod>.bin appear here.\n\
         pub static SNAPSHOTS: &[(&str, &str)] = &[\n",
    );
    for n in &names {
        let has_bin = bin_dir.join(format!("{n}.bin")).exists();
        if !has_bin {
            let path = snap_dir.join(format!("{n}.json"));
            writeln!(out, "    ({n:?}, include_str!({:?})),", path.display()).unwrap();
        }
    }
    out.push_str("];\n\n");

    // Binary table (fast runtime path). Only modules with a committed .bin.
    out.push_str(
        "/// (modname, postcard blob) pairs, sorted by modname for binary_search.\n\
         pub static SNAPSHOT_BINS: &[(&str, &[u8])] = &[\n",
    );
    for n in &names {
        let path = bin_dir.join(format!("{n}.bin"));
        if path.exists() {
            writeln!(out, "    ({n:?}, include_bytes!({:?})),", path.display()).unwrap();
        }
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("snapshot_data.rs");
    std::fs::write(dest, out).unwrap();
}
