// GENERATED by harness/gen_ext_templates.py from the pinned astroid
// 4.0.4 brain templates -- do not edit by hand.

pub static HASHLIB: &str = r#"
class md5:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'md5'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha1:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha1'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha224:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha224'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha256:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha256'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha384:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha384'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha512:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha512'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha3_224:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha3_224'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha3_256:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha3_256'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha3_384:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha3_384'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class sha3_512:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'sha3_512'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class shake_128:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self, length):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self, length):
        return ''
    @property
    def name(self):
        return 'shake_128'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class shake_256:
    def __init__(self, value='', usedforsecurity=True): pass
    def digest(self, length):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self, length):
        return ''
    @property
    def name(self):
        return 'shake_256'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class blake2b:
    def __init__(self, data=b'', *, digest_size=64, key=b'', salt=b'', person=b'', fanout=1, depth=1, leaf_size=0, node_offset=0, node_depth=0, inner_size=0, last_node=False, usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'blake2b'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1

class blake2s:
    def __init__(self, data=b'', *, digest_size=32, key=b'', salt=b'', person=b'', fanout=1, depth=1, leaf_size=0, node_offset=0, node_depth=0, inner_size=0, last_node=False, usedforsecurity=True): pass
    def digest(self):
        return b""
    def copy(self):
        return self
    def update(self, value): pass
    def hexdigest(self):
        return ''
    @property
    def name(self):
        return 'blake2s'
    @property
    def block_size(self):
        return 1
    @property
    def digest_size(self):
        return 1
"#;

pub static CRYPT: &str = r#"
from collections import namedtuple
_Method = namedtuple('_Method', 'name ident salt_chars total_size')

METHOD_SHA512 = _Method('SHA512', '6', 16, 106)
METHOD_SHA256 = _Method('SHA256', '5', 16, 63)
METHOD_BLOWFISH = _Method('BLOWFISH', 2, 'b', 22)
METHOD_MD5 = _Method('MD5', '1', 8, 34)
METHOD_CRYPT = _Method('CRYPT', None, 2, 13)
"#;

pub static SUBPROCESS: &str = r#"
def check_output(
    args, *,
    stdin=None,
    stderr=None,
    shell=False,
    cwd=None,
    encoding=None,
    errors=None,
    universal_newlines=False,
    timeout=None,
    env=None,
    text=None,
    restore_signals=True,
    preexec_fn=None,
    pass_fds=(),
    input=None,
    bufsize=0,
    executable=None,
    close_fds=False,
    startupinfo=None,
    creationflags=0,
    start_new_session=False
):
    if universal_newlines:
        return ""
    return b""

class Popen(object):
    returncode = pid = 0
    stdin = stdout = stderr = file()
    args = []

    def communicate(self, input=None, timeout=None):
        return (b'string', b'string')
    def wait(self, timeout=None):
        return self.returncode
    def poll(self):
        return self.returncode
    def send_signal(self, signal):
        pass
    def terminate(self):
        pass
    def kill(self):
        pass

    def __enter__(self): return self
    def __exit__(self, *args): pass

    @classmethod
    def __class_getitem__(cls, item):
        pass

    def __init__(        self, args, bufsize=-1, executable=None, stdin=None, stdout=None, stderr=None,
    preexec_fn=None, close_fds=True, shell=False, cwd=None, env=None,
    universal_newlines=None, startupinfo=None, creationflags=0, restore_signals=True,
    start_new_session=False, pass_fds=(), *, encoding=None, errors=None, text=None,
    user=None, group=None, extra_groups=None, umask=-1, pipesize=-1, process_group=None):
        pass"#;

pub static THREADING: &str = r#"
class lock(object):
    def acquire(self, blocking=True, timeout=-1):
        return False
    def release(self):
        pass
    def __enter__(self):
        return True
    def __exit__(self, *args):
        pass
    def locked(self):
        return False

def Lock(*args, **kwargs):
    return lock()
"#;

pub static SIGNAL: &str = r#"
import enum
class Signals(enum.IntEnum):
    SIGABRT   = enum.auto()
    SIGEMT    = enum.auto()
    SIGFPE    = enum.auto()
    SIGILL    = enum.auto()
    SIGINFO   = enum.auto()
    SIGINT    = enum.auto()
    SIGSEGV   = enum.auto()
    SIGTERM   = enum.auto()

    SIGALRM   = enum.auto()
    SIGBUS    = enum.auto()
    SIGCHLD   = enum.auto()
    SIGCONT   = enum.auto()
    SIGHUP    = enum.auto()
    SIGIO     = enum.auto()
    SIGIOT    = enum.auto()
    SIGKILL   = enum.auto()
    SIGPIPE   = enum.auto()
    SIGPROF   = enum.auto()
    SIGQUIT   = enum.auto()
    SIGSTOP   = enum.auto()
    SIGSYS    = enum.auto()
    SIGTRAP   = enum.auto()
    SIGTSTP   = enum.auto()
    SIGTTIN   = enum.auto()
    SIGTTOU   = enum.auto()
    SIGURG    = enum.auto()
    SIGUSR1   = enum.auto()
    SIGUSR2   = enum.auto()
    SIGVTALRM = enum.auto()
    SIGWINCH  = enum.auto()
    SIGXCPU   = enum.auto()
    SIGXFSZ   = enum.auto()

import enum
class Handlers(enum.IntEnum):
    SIG_DFL = enum.auto()
    SIG_IGN = eunm.auto()

import enum
class Sigmasks(enum.IntEnum):
    SIG_BLOCK   = enum.auto()
    SIG_UNBLOCK = enum.auto()
    SIG_SETMASK = enum.auto()
"#;

pub static SSL: &str = r#"
# Import necessary for conversion of objects defined in C into enums
from enum import IntEnum as _IntEnum, IntFlag as _IntFlag

from _ssl import OPENSSL_VERSION_NUMBER, OPENSSL_VERSION_INFO, OPENSSL_VERSION
from _ssl import _SSLContext, MemoryBIO
from _ssl import (
    SSLError, SSLZeroReturnError, SSLWantReadError, SSLWantWriteError,
    SSLSyscallError, SSLEOFError,
    )
from _ssl import CERT_NONE, CERT_OPTIONAL, CERT_REQUIRED
from _ssl import txt2obj as _txt2obj, nid2obj as _nid2obj
from _ssl import RAND_status, RAND_add, RAND_bytes, RAND_pseudo_bytes
try:
    from _ssl import RAND_egd
except ImportError:
    # LibreSSL does not provide RAND_egd
    pass
from _ssl import (OP_ALL, OP_CIPHER_SERVER_PREFERENCE,
                  OP_NO_COMPRESSION, OP_NO_SSLv2, OP_NO_SSLv3,
                  OP_NO_TLSv1, OP_NO_TLSv1_1, OP_NO_TLSv1_2,
                  OP_SINGLE_DH_USE, OP_SINGLE_ECDH_USE)

from _ssl import OP_LEGACY_SERVER_CONNECT

from _ssl import (ALERT_DESCRIPTION_ACCESS_DENIED, ALERT_DESCRIPTION_BAD_CERTIFICATE,
                  ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE,
                  ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE,
                  ALERT_DESCRIPTION_BAD_RECORD_MAC,
                  ALERT_DESCRIPTION_CERTIFICATE_EXPIRED,
                  ALERT_DESCRIPTION_CERTIFICATE_REVOKED,
                  ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN,
                  ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE,
                  ALERT_DESCRIPTION_CLOSE_NOTIFY, ALERT_DESCRIPTION_DECODE_ERROR,
                  ALERT_DESCRIPTION_DECOMPRESSION_FAILURE,
                  ALERT_DESCRIPTION_DECRYPT_ERROR,
                  ALERT_DESCRIPTION_HANDSHAKE_FAILURE,
                  ALERT_DESCRIPTION_ILLEGAL_PARAMETER,
                  ALERT_DESCRIPTION_INSUFFICIENT_SECURITY,
                  ALERT_DESCRIPTION_INTERNAL_ERROR,
                  ALERT_DESCRIPTION_NO_RENEGOTIATION,
                  ALERT_DESCRIPTION_PROTOCOL_VERSION,
                  ALERT_DESCRIPTION_RECORD_OVERFLOW,
                  ALERT_DESCRIPTION_UNEXPECTED_MESSAGE,
                  ALERT_DESCRIPTION_UNKNOWN_CA,
                  ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY,
                  ALERT_DESCRIPTION_UNRECOGNIZED_NAME,
                  ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE,
                  ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION,
                  ALERT_DESCRIPTION_USER_CANCELLED)
from _ssl import (SSL_ERROR_EOF, SSL_ERROR_INVALID_ERROR_CODE, SSL_ERROR_SSL,
                  SSL_ERROR_SYSCALL, SSL_ERROR_WANT_CONNECT, SSL_ERROR_WANT_READ,
                  SSL_ERROR_WANT_WRITE, SSL_ERROR_WANT_X509_LOOKUP, SSL_ERROR_ZERO_RETURN)
from _ssl import VERIFY_CRL_CHECK_CHAIN, VERIFY_CRL_CHECK_LEAF, VERIFY_DEFAULT, VERIFY_X509_STRICT
from _ssl import HAS_SNI, HAS_ECDH, HAS_NPN, HAS_ALPN
from _ssl import _OPENSSL_API_VERSION
from _ssl import PROTOCOL_SSLv23, PROTOCOL_TLSv1, PROTOCOL_TLSv1_1, PROTOCOL_TLSv1_2
from _ssl import PROTOCOL_TLS, PROTOCOL_TLS_CLIENT, PROTOCOL_TLS_SERVER

class AlertDescription(_IntEnum):
    ALERT_DESCRIPTION_ACCESS_DENIED = 0
    ALERT_DESCRIPTION_BAD_CERTIFICATE = 1
    ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE = 2
    ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE = 3
    ALERT_DESCRIPTION_BAD_RECORD_MAC = 4
    ALERT_DESCRIPTION_CERTIFICATE_EXPIRED = 5
    ALERT_DESCRIPTION_CERTIFICATE_REVOKED = 6
    ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN = 7
    ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE = 8
    ALERT_DESCRIPTION_CLOSE_NOTIFY = 9
    ALERT_DESCRIPTION_DECODE_ERROR = 10
    ALERT_DESCRIPTION_DECOMPRESSION_FAILURE = 11
    ALERT_DESCRIPTION_DECRYPT_ERROR = 12
    ALERT_DESCRIPTION_HANDSHAKE_FAILURE = 13
    ALERT_DESCRIPTION_ILLEGAL_PARAMETER = 14
    ALERT_DESCRIPTION_INSUFFICIENT_SECURITY = 15
    ALERT_DESCRIPTION_INTERNAL_ERROR = 16
    ALERT_DESCRIPTION_NO_RENEGOTIATION = 17
    ALERT_DESCRIPTION_PROTOCOL_VERSION = 18
    ALERT_DESCRIPTION_RECORD_OVERFLOW = 19
    ALERT_DESCRIPTION_UNEXPECTED_MESSAGE = 20
    ALERT_DESCRIPTION_UNKNOWN_CA = 21
    ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY = 22
    ALERT_DESCRIPTION_UNRECOGNIZED_NAME = 23
    ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE = 24
    ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION = 25
    ALERT_DESCRIPTION_USER_CANCELLED = 26

class SSLErrorNumber(_IntEnum):
    SSL_ERROR_EOF = 0
    SSL_ERROR_INVALID_ERROR_CODE = 1
    SSL_ERROR_SSL = 2
    SSL_ERROR_SYSCALL = 3
    SSL_ERROR_WANT_CONNECT = 4
    SSL_ERROR_WANT_READ = 5
    SSL_ERROR_WANT_WRITE = 6
    SSL_ERROR_WANT_X509_LOOKUP = 7
    SSL_ERROR_ZERO_RETURN = 8

class VerifyMode(_IntEnum):
    CERT_NONE = 0
    CERT_OPTIONAL = 1
    CERT_REQUIRED = 2

class VerifyFlags(_IntFlag):
    VERIFY_DEFAULT = 0
    VERIFY_CRL_CHECK_LEAF = 1
    VERIFY_CRL_CHECK_CHAIN = 2
    VERIFY_X509_STRICT = 3
    VERIFY_X509_TRUSTED_FIRST = 4
    VERIFY_ALLOW_PROXY_CERTS = 5
    VERIFY_X509_PARTIAL_CHAIN = 6

class Options(_IntFlag):
    OP_ALL = 1
    OP_NO_SSLv2 = 2
    OP_NO_SSLv3 = 3
    OP_NO_TLSv1 = 4
    OP_NO_TLSv1_1 = 5
    OP_NO_TLSv1_2 = 6
    OP_NO_TLSv1_3 = 7
    OP_CIPHER_SERVER_PREFERENCE = 8
    OP_SINGLE_DH_USE = 9
    OP_SINGLE_ECDH_USE = 10
    OP_NO_COMPRESSION = 11
    OP_NO_TICKET = 12
    OP_NO_RENEGOTIATION = 13
    OP_ENABLE_MIDDLEBOX_COMPAT = 14
    OP_LEGACY_SERVER_CONNECT = 15"#;

pub static RE: &str = r#"
import re._compiler as _compiler
NOFLAG = 0
ASCII = _compiler.SRE_FLAG_ASCII
IGNORECASE = _compiler.SRE_FLAG_IGNORECASE
LOCALE = _compiler.SRE_FLAG_LOCALE
UNICODE = _compiler.SRE_FLAG_UNICODE
MULTILINE = _compiler.SRE_FLAG_MULTILINE
DOTALL = _compiler.SRE_FLAG_DOTALL
VERBOSE = _compiler.SRE_FLAG_VERBOSE
TEMPLATE = _compiler.SRE_FLAG_TEMPLATE
DEBUG = _compiler.SRE_FLAG_DEBUG
A = ASCII
I = IGNORECASE
L = LOCALE
U = UNICODE
M = MULTILINE
S = DOTALL
X = VERBOSE
T = TEMPLATE
"#;

pub static HTTP: &str = r#"
from enum import IntEnum, StrEnum
from collections import namedtuple
_HTTPStatus = namedtuple('_HTTPStatus', 'value phrase description')

class HTTPMethod(StrEnum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    HEAD = "HEAD"
    OPTIONS = "OPTIONS"
    PATCH = "PATCH"
    TRACE = "TRACE"
    CONNECT = "CONNECT"

class HTTPStatus(IntEnum):

    @property
    def phrase(self):
        return ""
    @property
    def value(self):
        return 0
    @property
    def description(self):
        return ""

    # informational
    CONTINUE = _HTTPStatus(100, 'Continue', 'Request received, please continue')
    SWITCHING_PROTOCOLS = _HTTPStatus(101, 'Switching Protocols',
            'Switching to new protocol; obey Upgrade header')
    PROCESSING = _HTTPStatus(102, 'Processing', '')
    EARLY_HINTS = _HTTPStatus(103, 'Early Hints')
    OK = _HTTPStatus(200, 'OK', 'Request fulfilled, document follows')
    CREATED = _HTTPStatus(201, 'Created', 'Document created, URL follows')
    ACCEPTED = _HTTPStatus(202, 'Accepted',
        'Request accepted, processing continues off-line')
    NON_AUTHORITATIVE_INFORMATION = _HTTPStatus(203,
        'Non-Authoritative Information', 'Request fulfilled from cache')
    NO_CONTENT = _HTTPStatus(204, 'No Content', 'Request fulfilled, nothing follows')
    RESET_CONTENT =_HTTPStatus(205, 'Reset Content', 'Clear input form for further input')
    PARTIAL_CONTENT = _HTTPStatus(206, 'Partial Content', 'Partial content follows')
    MULTI_STATUS = _HTTPStatus(207, 'Multi-Status', '')
    ALREADY_REPORTED = _HTTPStatus(208, 'Already Reported', '')
    IM_USED = _HTTPStatus(226, 'IM Used', '')
    MULTIPLE_CHOICES = _HTTPStatus(300, 'Multiple Choices',
        'Object has several resources -- see URI list')
    MOVED_PERMANENTLY = _HTTPStatus(301, 'Moved Permanently',
        'Object moved permanently -- see URI list')
    FOUND = _HTTPStatus(302, 'Found', 'Object moved temporarily -- see URI list')
    SEE_OTHER = _HTTPStatus(303, 'See Other', 'Object moved -- see Method and URL list')
    NOT_MODIFIED = _HTTPStatus(304, 'Not Modified',
        'Document has not changed since given time')
    USE_PROXY = _HTTPStatus(305, 'Use Proxy',
        'You must use proxy specified in Location to access this resource')
    TEMPORARY_REDIRECT = _HTTPStatus(307, 'Temporary Redirect',
        'Object moved temporarily -- see URI list')
    PERMANENT_REDIRECT = _HTTPStatus(308, 'Permanent Redirect',
        'Object moved permanently -- see URI list')
    BAD_REQUEST = _HTTPStatus(400, 'Bad Request',
        'Bad request syntax or unsupported method')
    UNAUTHORIZED = _HTTPStatus(401, 'Unauthorized',
        'No permission -- see authorization schemes')
    PAYMENT_REQUIRED = _HTTPStatus(402, 'Payment Required',
        'No payment -- see charging schemes')
    FORBIDDEN = _HTTPStatus(403, 'Forbidden',
        'Request forbidden -- authorization will not help')
    NOT_FOUND = _HTTPStatus(404, 'Not Found',
        'Nothing matches the given URI')
    METHOD_NOT_ALLOWED = _HTTPStatus(405, 'Method Not Allowed',
        'Specified method is invalid for this resource')
    NOT_ACCEPTABLE = _HTTPStatus(406, 'Not Acceptable',
        'URI not available in preferred format')
    PROXY_AUTHENTICATION_REQUIRED = _HTTPStatus(407,
        'Proxy Authentication Required',
        'You must authenticate with this proxy before proceeding')
    REQUEST_TIMEOUT = _HTTPStatus(408, 'Request Timeout',
        'Request timed out; try again later')
    CONFLICT = _HTTPStatus(409, 'Conflict', 'Request conflict')
    GONE = _HTTPStatus(410, 'Gone',
        'URI no longer exists and has been permanently removed')
    LENGTH_REQUIRED = _HTTPStatus(411, 'Length Required',
        'Client must specify Content-Length')
    PRECONDITION_FAILED = _HTTPStatus(412, 'Precondition Failed',
        'Precondition in headers is false')
    CONTENT_TOO_LARGE = _HTTPStatus(413, 'Content Too Large',
    'Content is too large')
    REQUEST_ENTITY_TOO_LARGE = CONTENT_TOO_LARGE
    URI_TOO_LONG = _HTTPStatus(414, 'URI Too Long', 'URI is too long')
    REQUEST_URI_TOO_LONG = URI_TOO_LONG
    UNSUPPORTED_MEDIA_TYPE = _HTTPStatus(415, 'Unsupported Media Type',
        'Entity body in unsupported format')
    RANGE_NOT_SATISFIABLE = (416, 'Range Not Satisfiable',
    'Cannot satisfy request range')
    REQUESTED_RANGE_NOT_SATISFIABLE = RANGE_NOT_SATISFIABLE
    EXPECTATION_FAILED = _HTTPStatus(417, 'Expectation Failed',
        'Expect condition could not be satisfied')
    IM_A_TEAPOT = _HTTPStatus(418, 'I\'m a Teapot',
        'Server refuses to brew coffee because it is a teapot.')
    MISDIRECTED_REQUEST = _HTTPStatus(421, 'Misdirected Request',
        'Server is not able to produce a response')
    UNPROCESSABLE_CONTENT = _HTTPStatus(422, 'Unprocessable Content')
    UNPROCESSABLE_ENTITY = UNPROCESSABLE_CONTENT
    LOCKED = _HTTPStatus(423, 'Locked')
    FAILED_DEPENDENCY = _HTTPStatus(424, 'Failed Dependency')
    TOO_EARLY = _HTTPStatus(425, 'Too Early')
    UPGRADE_REQUIRED = _HTTPStatus(426, 'Upgrade Required')
    PRECONDITION_REQUIRED = _HTTPStatus(428, 'Precondition Required',
        'The origin server requires the request to be conditional')
    TOO_MANY_REQUESTS = _HTTPStatus(429, 'Too Many Requests',
        'The user has sent too many requests in '
        'a given amount of time ("rate limiting")')
    REQUEST_HEADER_FIELDS_TOO_LARGE = _HTTPStatus(431,
        'Request Header Fields Too Large',
        'The server is unwilling to process the request because its header '
        'fields are too large')
    UNAVAILABLE_FOR_LEGAL_REASONS = _HTTPStatus(451,
        'Unavailable For Legal Reasons',
        'The server is denying access to the '
        'resource as a consequence of a legal demand')
    INTERNAL_SERVER_ERROR = _HTTPStatus(500, 'Internal Server Error',
        'Server got itself in trouble')
    NOT_IMPLEMENTED = _HTTPStatus(501, 'Not Implemented',
        'Server does not support this operation')
    BAD_GATEWAY = _HTTPStatus(502, 'Bad Gateway',
        'Invalid responses from another server/proxy')
    SERVICE_UNAVAILABLE = _HTTPStatus(503, 'Service Unavailable',
        'The server cannot process the request due to a high load')
    GATEWAY_TIMEOUT = _HTTPStatus(504, 'Gateway Timeout',
        'The gateway server did not receive a timely response')
    HTTP_VERSION_NOT_SUPPORTED = _HTTPStatus(505, 'HTTP Version Not Supported',
        'Cannot fulfill request')
    VARIANT_ALSO_NEGOTIATES = _HTTPStatus(506, 'Variant Also Negotiates')
    INSUFFICIENT_STORAGE = _HTTPStatus(507, 'Insufficient Storage')
    LOOP_DETECTED = _HTTPStatus(508, 'Loop Detected')
    NOT_EXTENDED = _HTTPStatus(510, 'Not Extended')
    NETWORK_AUTHENTICATION_REQUIRED = _HTTPStatus(511,
        'Network Authentication Required',
        'The client needs to authenticate to gain network access')
"#;

pub static HTTP_CLIENT: &str = r#"
from http import HTTPStatus

CONTINUE = HTTPStatus.CONTINUE
SWITCHING_PROTOCOLS = HTTPStatus.SWITCHING_PROTOCOLS
PROCESSING = HTTPStatus.PROCESSING
EARLY_HINTS = HTTPStatus.EARLY_HINTS
OK = HTTPStatus.OK
CREATED = HTTPStatus.CREATED
ACCEPTED = HTTPStatus.ACCEPTED
NON_AUTHORITATIVE_INFORMATION = HTTPStatus.NON_AUTHORITATIVE_INFORMATION
NO_CONTENT = HTTPStatus.NO_CONTENT
RESET_CONTENT = HTTPStatus.RESET_CONTENT
PARTIAL_CONTENT = HTTPStatus.PARTIAL_CONTENT
MULTI_STATUS = HTTPStatus.MULTI_STATUS
ALREADY_REPORTED = HTTPStatus.ALREADY_REPORTED
IM_USED = HTTPStatus.IM_USED
MULTIPLE_CHOICES = HTTPStatus.MULTIPLE_CHOICES
MOVED_PERMANENTLY = HTTPStatus.MOVED_PERMANENTLY
FOUND = HTTPStatus.FOUND
SEE_OTHER = HTTPStatus.SEE_OTHER
NOT_MODIFIED = HTTPStatus.NOT_MODIFIED
USE_PROXY = HTTPStatus.USE_PROXY
TEMPORARY_REDIRECT = HTTPStatus.TEMPORARY_REDIRECT
PERMANENT_REDIRECT = HTTPStatus.PERMANENT_REDIRECT
BAD_REQUEST = HTTPStatus.BAD_REQUEST
UNAUTHORIZED = HTTPStatus.UNAUTHORIZED
PAYMENT_REQUIRED = HTTPStatus.PAYMENT_REQUIRED
FORBIDDEN = HTTPStatus.FORBIDDEN
NOT_FOUND = HTTPStatus.NOT_FOUND
METHOD_NOT_ALLOWED = HTTPStatus.METHOD_NOT_ALLOWED
NOT_ACCEPTABLE = HTTPStatus.NOT_ACCEPTABLE
PROXY_AUTHENTICATION_REQUIRED = HTTPStatus.PROXY_AUTHENTICATION_REQUIRED
REQUEST_TIMEOUT = HTTPStatus.REQUEST_TIMEOUT
CONFLICT = HTTPStatus.CONFLICT
GONE = HTTPStatus.GONE
LENGTH_REQUIRED = HTTPStatus.LENGTH_REQUIRED
PRECONDITION_FAILED = HTTPStatus.PRECONDITION_FAILED
CONTENT_TOO_LARGE = HTTPStatus.CONTENT_TOO_LARGE
REQUEST_ENTITY_TOO_LARGE = HTTPStatus.CONTENT_TOO_LARGE
URI_TOO_LONG = HTTPStatus.URI_TOO_LONG
REQUEST_URI_TOO_LONG = HTTPStatus.URI_TOO_LONG
UNSUPPORTED_MEDIA_TYPE = HTTPStatus.UNSUPPORTED_MEDIA_TYPE
RANGE_NOT_SATISFIABLE = HTTPStatus.RANGE_NOT_SATISFIABLE
REQUESTED_RANGE_NOT_SATISFIABLE = HTTPStatus.RANGE_NOT_SATISFIABLE
EXPECTATION_FAILED = HTTPStatus.EXPECTATION_FAILED
IM_A_TEAPOT = HTTPStatus.IM_A_TEAPOT
UNPROCESSABLE_CONTENT = HTTPStatus.UNPROCESSABLE_CONTENT
UNPROCESSABLE_ENTITY = HTTPStatus.UNPROCESSABLE_CONTENT
LOCKED = HTTPStatus.LOCKED
FAILED_DEPENDENCY = HTTPStatus.FAILED_DEPENDENCY
TOO_EARLY = HTTPStatus.TOO_EARLY
UPGRADE_REQUIRED = HTTPStatus.UPGRADE_REQUIRED
PRECONDITION_REQUIRED = HTTPStatus.PRECONDITION_REQUIRED
TOO_MANY_REQUESTS = HTTPStatus.TOO_MANY_REQUESTS
REQUEST_HEADER_FIELDS_TOO_LARGE = HTTPStatus.REQUEST_HEADER_FIELDS_TOO_LARGE
INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
NOT_IMPLEMENTED = HTTPStatus.NOT_IMPLEMENTED
BAD_GATEWAY = HTTPStatus.BAD_GATEWAY
SERVICE_UNAVAILABLE = HTTPStatus.SERVICE_UNAVAILABLE
GATEWAY_TIMEOUT = HTTPStatus.GATEWAY_TIMEOUT
HTTP_VERSION_NOT_SUPPORTED = HTTPStatus.HTTP_VERSION_NOT_SUPPORTED
VARIANT_ALSO_NEGOTIATES = HTTPStatus.VARIANT_ALSO_NEGOTIATES
INSUFFICIENT_STORAGE = HTTPStatus.INSUFFICIENT_STORAGE
LOOP_DETECTED = HTTPStatus.LOOP_DETECTED
NOT_EXTENDED = HTTPStatus.NOT_EXTENDED
NETWORK_AUTHENTICATION_REQUIRED = HTTPStatus.NETWORK_AUTHENTICATION_REQUIRED
"#;

pub static MP_MANAGERS: &str = r#"
import array
import threading
import multiprocessing.pool as pool
import queue

class Namespace(object):
    pass

class Value(object):
    def __init__(self, typecode, value, lock=True):
        self._typecode = typecode
        self._value = value
    def get(self):
        return self._value
    def set(self, value):
        self._value = value
    def __repr__(self):
        return '%s(%r, %r)'%(type(self).__name__, self._typecode, self._value)
    value = property(get, set)

def Array(typecode, sequence, lock=True):
    return array.array(typecode, sequence)

class SyncManager(object):
    Queue = JoinableQueue = queue.Queue
    Event = threading.Event
    RLock = threading.RLock
    Lock = threading.Lock
    BoundedSemaphore = threading.BoundedSemaphore
    Condition = threading.Condition
    Barrier = threading.Barrier
    Pool = pool.Pool
    list = list
    dict = dict
    Value = Value
    Array = Array
    Namespace = Namespace
    __enter__ = lambda self: self
    __exit__ = lambda *args: args

    def start(self, initializer=None, initargs=None):
        pass
    def shutdown(self):
        pass
"#;

pub static UNITTEST: &str = r#"
from unittest.async_case import IsolatedAsyncioTestCase
"#;

pub static MP_TEMPLATE: &str = r#"
from multiprocessing.managers import SyncManager
def Manager():
    return SyncManager()
"#;

pub static MP_PROBE: &str = r#"
from multiprocessing.context import DefaultContext, BaseContext
default = DefaultContext()
base = BaseContext()
"#;

/// (target module name, template source) in astroid registration order.
/// multiprocessing handled separately (BM probe).
pub static EXTENDERS: &[(&str, &str)] = &[
    ("hashlib", HASHLIB),
    ("crypt", CRYPT),
    ("subprocess", SUBPROCESS),
    ("threading", THREADING),
    ("signal", SIGNAL),
    ("ssl", SSL),
    ("re", RE),
    ("http", HTTP),
    ("http.client", HTTP_CLIENT),
    ("multiprocessing.managers", MP_MANAGERS),
    ("unittest", UNITTEST),
];
